/* ../../../c.pass2/p2_01.c */
int main(int argc, char **argv);
expnode *L0787(void);
void L095c(double *dblptr);
void openoutpth(char *fnam);
void L0a16(expnode *cref, int parm2);
void psh_stk(char *parm);
void err_exit(void);
int getword(FILE *fp);
/* ../../../c.pass2/p2_02.c */
void L0bc3(expnode *cref);
void L0bf7(expnode *cref);
void L0c2d(expnode *cref);
void L0c6d(expnode *cref);
expnode *L0d04(expnode *cref);
void L0efd(int vtyp, expnode *cref);
int L121f(int cmd_val);
void L124c(expnode *cref);
void L12e8(expnode *cref, void (*fnc)(void));
void L1364(expnode *cref);
int L1440(expnode *cref);
int L149e(expnode *cref);
int L14da(expnode *cref);
int L14f2(expnode *cref);
void L152d(expnode *cref);
void L1567(expnode *cref);
void L16cb(expnode *cref, int vartype);
void L1904(expnode *cref);
void L1953(expnode *cref);
void L1a9a(expnode *cref, int val);
void L1be4(expnode *cref);
void L1c1d(expnode *cref);
int is_regvar(int vtyp);
/* ../../../c.pass2/p2_03.c */
void L1f13(expnode *cref, int parm2, int parm3, int parm4);
void L20ed(int parm1, expnode *cref, int parm3, int parm4, int parm5);
int L22ca(expnode *cref);
void L2323(expnode *cref);
int L2466(int parm1);
int L249e(int parm1);
int L24e6(expnode *cref);
void L2505(expnode *cref);
void L2520(expnode *cref);
void L28fb(expnode *cref);
void L294b(expnode *cref);
/* ../../../c.pass2/p2_04.c */
void L29fc(expnode *cref);
void L2a17(expnode *cref);
/* ../../../c.pass2/p2_06.c */
void *getmem(int siz);
void L3203(struct val_data *vdat, int siz);
void gen(int op, int rtype, int arg, expnode *val);
int get_regname(int parm1);
void L39d9(int parm1, int parm2);
void L3bc2(int parm1, int fttyp);
void L3d90(int fttyp, int siz);
void L3dd0(int *intarray, int siz);
void L3e51(char *strng);
void L3e6e(char *strng);
void L3e8d(char *strng);
void L3ea4(int parm1, int parm2, expnode *cref);
void L4085(int ch, int parm2, int parm3, int parm4);
void L40af(int parm1);
void L40d0(int parm1, int parm2, int parm3);
char *br_rel_op(int vtype);
void prt_bgnfld(char *opcod);
void L43d1(char *opcod);
void L43dc(void);
void prnt_chr(int ch);
void prnt_strng(char *strng);
void prnt_integer(int valu);
void L4414(int valu);
void prt_loclbl(int valu);
void prt_lblnam(char *lblnam);
int prt_rsrvstk(int valu);
void prt_label(char *lblnam, int isglbl);
void lea_reg(int reg);
void lea_llblpcr(int regnam, int lblnum);
/* ../../../c.pass2/p2_07.c */
void L4823(char *strng);
void outofmemory(void);
void L484b(expnode *cref, char *strng);
void L487f(expnode *cref, char *parm2);
void L4896(int parm1, long lng);
long *lng2_flacc(int parm1);
int L4938(int srclin, char *parm2, long *lngptr);
void L4a69(expnode *cref);
void L4a8a(expnode *cref);
void L4acd(expnode *parm1, expnode *parm2);
int L4af7(int parm1);
void ncpystr(char *src, char *dest, int count);
/* ../../../c.pass2/p2_08.c */
void prt_fdb(void);
void prt_funcbegin(char *title, char *funcnam, int parm3, int parm4);
void prtstkreq(void);
void prtvsctbgn(int isdp);
void prtendsect(void);
void L4c61(void);
void L4c92(int parm);
/* ../../../c.pass2/printf.c */
int _printf(char *fmt, int vals);
int _fprintf(FILE *fp, char *fmt, int vals);
int _sprintf(char *fp, char *fmt, int vals);
void L2d8c(register char *fmt, int *_vals);
char *_dec2str(int _nmbr);
void todigit(char *str, int valu);
char *_hex2str(unsigned int _nbr);
void outputfld(char *strng, register int fld_wdth);
void L5415(register char *regpt, int str_lngth, int __fldwdth);
void sendchar(int p1);
