/* ../../../c.pass1/build.c */
expnode *parsexp(int priority);
expnode *L0694(void);
expnode *explist(void);
int constexp(int p);
int isop(void);
int constop(int op, int r, int l);
expnode *getcast(void);
expnode *newnode(int op, expnode *left, expnode *right, int value, int lno, char *errpnt);
void exprmsng(void);
/* ../../../c.pass1/cmain.c */
int main(int argc, char **argv);
void quit_cc(void);
/* ../../../c.pass1/declare.c */
void extdef(void);
void argdef(void);
void blkdef(void);
int declrcmp(symnode *ptr, int type, elem *eptr);
int chkreg(int sclass_result, int fty);
void newfunc(symnode *fptr, int sclass);
void block(void);
void declist(symnode **list);
int setclass(void);
int settype(int *siz, dimnode **dimptr, elem **ellist);
int declarator(symnode **ptr, dimnode **dptr, int bastype);
int shiftin(int p1, int p2);
int sizeup(symnode *ptr, dimnode *dimptr, int size);
int getsize(int t, int size, dimnode *dptr);
void clear(symnode **list);
void sizundef(void);
void noidentf(void);
/* ../../../c.pass1/get.c */
void initbuf0(void);
void skipblank(void);
void getnxtch(void);
char prepln(void);
int a_toi(char *cptr);
char *gtnxtlin(void);
/* ../../../c.pass1/inits.c */
void initialize(symnode *ptr, int tsc, int type);
void zero(int p1);
int defobject(int type);
void datdef(int valu, int f_type);
void cant_init(void);
void find_sep(void);
/* ../../../c.pass1/lex.c */
void nxt_word(void);
void tblsetup(void);
void fget_lbl(char *_dst);
int islblchr(int pos);
symnode *FindLbl(char *name);
void inizFTbl(char *name, int type);
unsigned int str_sum(char *nam);
void *addmem(int siz);
int number(int p1, void *dest_val);
void do_squot(void);
void do_dquot(void);
void addstrchr(int p1);
void prnt_rzb(int valu);
int dobkslsh(void);
int is_octal(char ch);
int is_hex(char ch);
/* ../../../c.pass1/local.c */
void dumpstrings(void);
void rmbnolbl(int p1, int valu, int p3);
void globldata(symnode *p1, int p2, int p3);
void localdata(symnode *p1, int p2, int p3);
void lbl_rmb(symnode *p1, int p2, char _colon);
void prtstkchk(char *funcnam, int p2, int p3);
void prtprofil(char *p1, int p2);
void flgstkchk(void);
void prnt_fcb(void);
void prnt_fdb(void);
void pr2stars(void);
void wdataflag(int p1);
void putc_e(void);
int seek0_FP(FILE *_fp);
void dumpstrs(void);
void quitcc(void);
/* ../../../c.pass1/misc.c */
void pushdown(symnode *sptr);
void pullup(symnode *sptr);
void mem_cp(void *_src, void *_dest, int siz);
void prnt_filname(void);
int fatal(char *p1);
void multdef(void);
void reprterr(char *_str);
void comperr(expnode *p1, char *_errmsg);
void terror(expnode *p1, char *_errmsg);
void doerr(int _linpos, char *txt, int _line);
void displerr(char *pmpt, void *val);
void e_putlin(char *str);
void e_putc(char ch);
void reltree(expnode *tree);
void release(expnode *p1);
void nodecopy(char *p1, char *p2);
int istype(void);
int issclass(void);
int decref(int p1);
int incref(int p1);
int isbin(int p1);
dimnode *dimwalk(dimnode *dptr);
int need(int needed);
void junk(void);
/* ../../../c.pass1/optim.c */
expnode *optim(expnode *tree);
expnode *fold(expnode *tree);
int isleaf(expnode *node);
void divby_0(void);
expnode *chtype(expnode *node);
void cknull(expnode *regptr);
int cktypnumeric(expnode *c_ref);
int do_cast(expnode *node, int t);
int tymatch(expnode *lhs, expnode *rhs);
expnode *fixup(int size, int t, expnode *dptr, expnode *rhs);
void needlval(expnode *node, int flag);
void ck_declared(expnode *regptr);
int needmos(expnode *node, int *t, int *mosar);
int get_ftty(expnode *regptr);
void makedummy(expnode *p1);
int iswordorlong(int tstval);
void notintegral(expnode *c_ref);
/* ../../../c.pass1/p1_07.c */
void prtlbl(char *lbnm, int isglbl);
void prtspstr(char *str);
void prt_not_used(char *str);
void prntCR(void);
void printchr(int ch);
void prntstring(char *str);
void prntdgt(int num);
void uselabel(int wrd);
void prtlcllbl(int nbr);
void wrtunderscore(int nbr);
void prtlbnm(char *lbl);
int wrt_M(int nbr);
void gen(int parm, int par2, int par3);
void prntstar(void);
void prntfnam(char *str);
expnode *ld_exp(expnode *parm);
expnode *prt_4c2c(expnode *p1, int p2, int p3, int p4);
expnode *transexp(expnode *cmdrf);
void prt_4c68(int addflg, expnode *cmdrf, int p3, int p4, int p5);
int calc_value(expnode *wp, int _flg);
void wrtallinfo(expnode *wp);
void wrt_info(expnode *wp);
void prntnuls(int *valu, int countflg);
int prt_float(char *data_val, int f_type);
int prt_509e(expnode *p1, int p2);
/* ../../../c.pass1/printf.c */
int _printf(char *fmt, int vals);
int _fprintf(FILE *fp, char *fmt, int vals);
int _sprintf(char *fp, char *fmt, int vals);
void L511b(char *fmt, int *_vals);
char *_dec2str(int _nmbr);
void todigit(char *str, int valu);
char *_hex2str(unsigned int _nbr);
void outputfld(char *strng, int fld_wdth);
void L5415(char *regpt, int str_lngth, int __fldwdth);
void sendchar(int p1);
/* ../../../c.pass1/stats.c */
void statement(void);
void do_if(void);
void do_while(void);
void do_swtch(void);
void do_case(void);
void do_deflt(void);
void no_switch(void);
void do_do(void);
void do_for(void);
void do_retrn(void);
void do_break(void);
void do_contin(void);
void do_goto(void);
void dotest(expnode *regptr, int p2, int p3, int p4);
